/* Simulation code for RoverExample.Components.Rover generated by the OpenModelica Compiler OpenModelica 1.25.0~2-ge56b89b. */
#if !defined(RoverExample_Components_Rover__MODEL_H)
#define RoverExample_Components_Rover__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "RoverExample.Components.Rover_functions.h"

#define _omcQ_24DER_24RoverExample_24PUtils_24Peul2rot_index 0
#define RoverExample_Utils_avoidzero_index 1
#define RoverExample_Utils_clip_index 2
#define RoverExample_Utils_cross3_index 3
#define RoverExample_Utils_dot3_index 4
#define RoverExample_Utils_eul2rot_index 5

extern void RoverExample_Components_Rover_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void RoverExample_Components_Rover_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void RoverExample_Components_Rover_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void RoverExample_Components_Rover_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int RoverExample_Components_Rover_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_checkForAsserts(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int RoverExample_Components_Rover_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* RoverExample_Components_Rover_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* RoverExample_Components_Rover_relationDescription(int i);
extern void RoverExample_Components_Rover_function_initSample(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int RoverExample_Components_Rover_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int RoverExample_Components_Rover_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int RoverExample_Components_Rover_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int RoverExample_Components_Rover_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int RoverExample_Components_Rover_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int RoverExample_Components_Rover_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int RoverExample_Components_Rover_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int RoverExample_Components_Rover_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int RoverExample_Components_Rover_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int RoverExample_Components_Rover_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int RoverExample_Components_Rover_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int RoverExample_Components_Rover_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int RoverExample_Components_Rover_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* RoverExample_Components_Rover_linear_model_frame(void);
extern const char* RoverExample_Components_Rover_linear_model_datarecovery_frame(void);
extern int RoverExample_Components_Rover_mayer(DATA* data, modelica_real** res, short *);
extern int RoverExample_Components_Rover_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int RoverExample_Components_Rover_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int RoverExample_Components_Rover_setInputData(DATA *data, const modelica_boolean file);
extern int RoverExample_Components_Rover_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void RoverExample_Components_Rover_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void RoverExample_Components_Rover_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int RoverExample_Components_Rover_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void RoverExample_Components_Rover_read_simulation_info(SIMULATION_INFO* simulationData);
extern void RoverExample_Components_Rover_read_input_fmu(MODEL_DATA* modelData);
extern void RoverExample_Components_Rover_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int RoverExample_Components_Rover_inputNames(DATA* data, char ** names);
extern int RoverExample_Components_Rover_dataReconciliationInputNames(DATA* data, char ** names);
extern int RoverExample_Components_Rover_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int RoverExample_Components_Rover_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int RoverExample_Components_Rover_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int RoverExample_Components_Rover_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "RoverExample.Components.Rover_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(RoverExample_Components_Rover__MODEL_H) */


