/* Additional record code for RoverExample.Components.Controller generated by the OpenModelica Compiler OpenModelica 1.25.0~2-ge56b89b. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "RoverExample.Components.Controller_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

